# Generated by Django 4.1 on 2022-11-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hospital_logo', models.ImageField(blank=True, null=True, upload_to='images/configuration/%Y')),
                ('hospital_name', models.CharField(max_length=150, null=True)),
                ('hospital_website', models.CharField(max_length=200, null=True)),
                ('hospital_email', models.CharField(max_length=200, null=True)),
                ('hospital_phone', models.CharField(max_length=200, null=True)),
                ('hospital_slogan', models.CharField(max_length=200, null=True)),
                ('hospital_greetings', models.CharField(max_length=200, null=True)),
                ('hospital_address1', models.CharField(max_length=200, null=True)),
                ('hospital_address2', models.CharField(max_length=200, null=True)),
                ('hospital_pincode', models.CharField(max_length=200, null=True)),
                ('hospital_gst', models.CharField(max_length=200, null=True)),
                ('hospital_registeration_number', models.CharField(max_length=200, null=True)),
                ('hospital_druglicense_number', models.CharField(max_length=200, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'App Configuration',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
