# Generated by Django 4.1 on 2022-11-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_appconfiguration_hospital_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfiguration',
            name='hospital_logo1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
