# Generated by Django 4.1 on 2022-11-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_appconfiguration_hospital_logo1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfiguration',
            name='hospital_logo1',
        ),
    ]
