# Generated by Django 4.1.3 on 2023-01-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_appconfiguration_default_doctorfees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfiguration',
            name='hospital_greetings',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
