# Generated by Django 4.1.2 on 2023-06-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_alter_appconfiguration_default_doctorfees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfiguration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
