# Generated by Django 4.0.6 on 2022-12-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=150, null=True)),
                ('gender', models.CharField(max_length=150, null=True)),
                ('father_name', models.CharField(max_length=150, null=True)),
                ('dob', models.DateTimeField(null=True)),
                ('village', models.CharField(max_length=150, null=True)),
                ('district', models.CharField(max_length=150, null=True)),
                ('state', models.CharField(max_length=150, null=True)),
                ('pincode', models.CharField(max_length=150, null=True)),
                ('purpose_of', models.CharField(max_length=150, null=True)),
                ('date', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Forms',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
