# Generated by Django 4.0.6 on 2022-12-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_alter_forms_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
