# Generated by Django 4.1 on 2022-09-19 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_gender'),
        ('room', '0002_remove_in_patient_paymenttransactions_assignroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IN_Patient_Payments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('doctor_fees', models.IntegerField(default=0, null=True)),
                ('injection', models.IntegerField(default=0, null=True)),
                ('service', models.IntegerField(default=0, null=True)),
                ('others', models.IntegerField(default=0, null=True)),
                ('lab', models.IntegerField(default=0, null=True)),
                ('xray', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('paid', models.IntegerField(default=0, null=True)),
                ('balance', models.IntegerField(default=0, null=True)),
                ('cash', models.IntegerField(default=0, null=True)),
                ('upi', models.IntegerField(default=0, null=True)),
                ('card', models.IntegerField(default=0, null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('assignroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='room.assignrooms')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient')),
            ],
            options={
                'verbose_name_plural': 'IN_Patient_Payments',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='IN_Patient_PaymentTransactions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.IntegerField(default=0, null=True)),
                ('existing_balance', models.IntegerField(default=0, null=True)),
                ('paid', models.IntegerField(default=0, null=True)),
                ('balance', models.IntegerField(default=0, null=True)),
                ('cash', models.IntegerField(default=0, null=True)),
                ('upi', models.IntegerField(default=0, null=True)),
                ('card', models.IntegerField(default=0, null=True)),
                ('payment_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('assignroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='room.assignrooms')),
                ('ip_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='room.in_patient_payments')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient')),
            ],
            options={
                'verbose_name_plural': 'IN_Patient_PaymentTransactions',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
