# Generated by Django 4.1 on 2022-09-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_injectionforinpatient_injection_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_patient_payments',
            name='rooms',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
