# Generated by Django 4.1 on 2022-09-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_in_patient_payments_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='in_patient_payments',
            old_name='rooms',
            new_name='room',
        ),
    ]
