# Generated by Django 4.1 on 2022-09-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_rename_rooms_in_patient_payments_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_patient_payments',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
