# Generated by Django 4.1 on 2022-09-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_in_patient_payments_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_patient_paymenttransactions',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
