# Generated by Django 4.1 on 2022-09-24 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_gender'),
        ('doctor', '0003_alter_doctor_role'),
        ('room', '0008_in_patient_paymenttransactions_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary_IN',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_surgery', models.DateTimeField(null=True)),
                ('allergies', models.CharField(max_length=500, null=True)),
                ('diagnosis', models.CharField(max_length=500, null=True)),
                ('investigations', models.CharField(max_length=500, null=True)),
                ('treatment', models.CharField(max_length=500, null=True)),
                ('advice_on_discharge', models.CharField(max_length=500, null=True)),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doctor.doctor')),
                ('ip_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='room.assignrooms')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient')),
                ('room_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='room.rooms')),
            ],
            options={
                'verbose_name_plural': 'DischargeSummary_IN',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
