# Generated by Django 4.1 on 2022-09-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_dischargesummary_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dischargesummary_in',
            old_name='room_no',
            new_name='room',
        ),
        migrations.AddField(
            model_name='dischargesummary_in',
            name='created_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dischargesummary_in',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
