# Generated by Django 4.1 on 2022-09-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0010_rename_room_no_dischargesummary_in_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dischargesummary_in',
            old_name='investigations',
            new_name='investigation',
        ),
    ]
