# Generated by Django 4.1 on 2022-09-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_alter_dressingforinpatient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_patient_payments',
            name='total_after_discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='in_patient_paymenttransactions',
            name='total_after_discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
