# Generated by Django 4.0.6 on 2022-10-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0015_remove_assignrooms_doctor_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctercheckup',
            name='medical_prescription',
            field=models.TextField(default='', null=True),
        ),
    ]
