# Generated by Django 4.1 on 2022-10-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0016_doctercheckup_medical_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='in_patient_payments',
            old_name='others',
            new_name='consultant_charges',
        ),
        migrations.RenameField(
            model_name='in_patient_payments',
            old_name='service',
            new_name='dressing_charges',
        ),
        migrations.AddField(
            model_name='in_patient_payments',
            name='establishment_charges',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='in_patient_payments',
            name='icu_charges',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='in_patient_payments',
            name='iv_fluid_charges',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='in_patient_payments',
            name='miscellaneous_charges',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='in_patient_payments',
            name='nursing_charge',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='in_patient_payments',
            name='physiotherapy_charges',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='in_patient_payments',
            name='surgery_charges',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
