# Generated by Django 4.0.6 on 2022-11-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_rename_others_in_patient_payments_consultant_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_patient_payments',
            name='payment_recived_by_lab',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
