# Generated by Django 4.0.6 on 2022-11-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0018_in_patient_payments_payment_recived_by_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_patient_payments',
            name='total_lab_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
