# Generated by Django 4.0.3 on 2022-11-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0021_in_patient_paymenttransactions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignrooms',
            name='balance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assignrooms',
            name='paid',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assignrooms',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='in_patient_payments',
            name='payment_recived_by_xray',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
