# Generated by Django 4.0.6 on 2022-12-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0024_in_patient_paymenttransactions_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True)),
                ('category', models.CharField(max_length=150, null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
