# Generated by Django 4.0.6 on 2022-12-06 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0025_roomcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='room.roomcategory'),
        ),
    ]
