# Generated by Django 4.0.6 on 2022-12-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0026_rooms_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomcategory',
            options={'default_permissions': (), 'ordering': ['id'], 'verbose_name_plural': 'RoomCategory'},
        ),
        migrations.AddField(
            model_name='labtestforinpatient',
            name='lab_canceled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
