# Generated by Django 4.0.6 on 2023-01-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0031_assignrooms_balance_from_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctercheckup',
            name='sale_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
