# Generated by Django 4.0.6 on 2023-01-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0032_doctercheckup_sale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_patient_payments',
            name='refund',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
