# Generated by Django 4.0.6 on 2023-01-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0033_in_patient_payments_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_patient_payments',
            name='refund_note',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='in_patient_payments',
            name='refund_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
