# Generated by Django 4.0.6 on 2023-02-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0034_in_patient_payments_refund_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestforinpatient',
            name='payment_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
