# Generated by Django 4.0.6 on 2023-02-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0035_labtestforinpatient_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestforinpatient',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='labtestforinpatient',
            name='payment_complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
