# Generated by Django 4.0.6 on 2023-02-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0036_remove_labtestforinpatient_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestforinpatient',
            name='payment_complete',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
