# Generated by Django 4.0.6 on 2023-02-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_user_staff_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
