# Generated by Django 4.0.3 on 2022-11-24 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0003_patient_pos_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedReports',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('url', models.ImageField(null=True, upload_to='images/uploaded_reports/%Y')),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient')),
            ],
            options={
                'verbose_name_plural': 'Uploaded Reports',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
