# Generated by Django 4.0.3 on 2022-11-24 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedreports',
            name='url',
        ),
        migrations.CreateModel(
            name='UploadedReportsFiles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.ImageField(null=True, upload_to='images/uploaded_reports/%Y')),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('uploded_reports', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='upload_reports.uploadedreports')),
            ],
            options={
                'verbose_name_plural': 'Uploaded Reports Files',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
