# Generated by Django 4.0.6 on 2023-02-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_reports', '0002_remove_uploadedreports_url_uploadedreportsfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedreports',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedreports',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedreportsfiles',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedreportsfiles',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
