# Generated by Django 4.1.2 on 2023-06-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_reports', '0006_alter_uploadedreports_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedreports',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadedreportsfiles',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
