# Generated by Django 4.0.5 on 2022-08-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0002_xrayforpatient_xraytakenbypatient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xraytakenbypatient',
            name='amount',
        ),
    ]
