# Generated by Django 4.1 on 2022-09-19 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_in_patient_payments_in_patient_paymenttransactions'),
        ('xray', '0003_remove_xraytakenbypatient_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayforpatient',
            name='assignroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='room.assignrooms'),
        ),
        migrations.AddField(
            model_name='xrayforpatient',
            name='ip_xray_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='room.xrayforinpatient'),
        ),
        migrations.AddField(
            model_name='xrayforpatient',
            name='patient_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
