# Generated by Django 4.1 on 2022-09-23 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0004_assignward_checkup_assignward_doctor_prescription_and_more'),
        ('xray', '0004_xrayforpatient_assignroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayforpatient',
            name='assignward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ward.assignward'),
        ),
        migrations.AddField(
            model_name='xrayforpatient',
            name='ward_xray_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ward.xrayforwardpatient'),
        ),
    ]
