# Generated by Django 4.1 on 2022-09-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0005_xrayforpatient_assignward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xrayforpatient',
            name='from_op',
        ),
    ]
