# Generated by Django 4.0.3 on 2022-11-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0006_remove_xrayforpatient_from_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='xrayforpatient',
            name='balance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='xrayforpatient',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='xrayforpatient',
            name='initially_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
