# Generated by Django 4.0.3 on 2022-11-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0008_xrayforpatient_card_xrayforpatient_cash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xraypaymenttransaction',
            old_name='xray_for_general_patient',
            new_name='xray_for_patient',
        ),
    ]
