# Generated by Django 4.1.2 on 2023-06-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0013_alter_xray_id_alter_xrayforpatient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xray',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='xrayforpatient',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='xraypaymenttransaction',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='xraytakenbypatient',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
