# Generated by Django 4.0.3 on 2022-08-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='has_lab',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='has_xray',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='lab_test',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='xray_test',
            field=models.JSONField(null=True),
        ),
    ]
