# Generated by Django 4.0.3 on 2022-08-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_has_lab_appointment_has_xray_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_prescription',
            field=models.TextField(default='', null=True),
        ),
    ]
