# Generated by Django 4.0.3 on 2022-08-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_appointment_doctor_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='lab_checked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='xray_checked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
