# Generated by Django 4.0.3 on 2022-08-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_lab_checked_appointment_xray_checked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='checkup',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
