# Generated by Django 4.0.5 on 2022-08-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_initially_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medicine_list',
            field=models.JSONField(null=True),
        ),
    ]
