# Generated by Django 4.0.5 on 2022-08-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_outpatient_payments_outpatient_paymenttransactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outpatient_payments',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='outpatient_payments',
            name='lab',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='outpatient_payments',
            name='xray',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='outpatient_payments',
            name='created_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='outpatient_payments',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='outpatient_paymenttransactions',
            name='created_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='outpatient_paymenttransactions',
            name='payment_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='outpatient_paymenttransactions',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
