# Generated by Django 4.0.5 on 2022-08-30 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_gender'),
        ('appointment', '0012_remove_xrayforoutpatient_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='lab_checked',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='lab_test',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='xray_checked',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='xray_test',
        ),
        migrations.AddField(
            model_name='outpatient_payments',
            name='card',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='outpatient_payments',
            name='lab',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='outpatient_payments',
            name='xray',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='outpatient_paymenttransactions',
            name='card',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='XrayForOutPatient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('xray_test', models.JSONField(null=True)),
                ('xray_checked', models.BooleanField(default=False, null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.appointment')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient')),
            ],
            options={
                'verbose_name_plural': 'XrayForOutPatient',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LabTestForOutPatient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lab_test', models.JSONField(null=True)),
                ('lab_checked', models.BooleanField(default=False, null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.appointment')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient')),
            ],
            options={
                'verbose_name_plural': 'LabTestForOutPatient',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
