# Generated by Django 4.0.5 on 2022-08-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_remove_appointment_lab_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestforoutpatient',
            name='lab_test_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='xrayforoutpatient',
            name='xray_test_date',
            field=models.DateTimeField(null=True),
        ),
    ]
