# Generated by Django 4.0.5 on 2022-08-31 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_gender'),
        ('appointment', '0016_labtestforoutpatient_lab_test_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='medicine_list',
        ),
        migrations.CreateModel(
            name='MedicineForOutPatient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('medicine_list', models.JSONField(null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.appointment')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient')),
            ],
            options={
                'verbose_name_plural': 'MedicineForOutPatient',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
