# Generated by Django 4.1 on 2022-09-02 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_gender'),
        ('appointment', '0017_remove_appointment_medicine_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionForOutPatient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('injection_list', models.JSONField(null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('appointment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.appointment')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient')),
            ],
            options={
                'verbose_name_plural': 'InjectionForOutPatient',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
