# Generated by Django 4.1 on 2022-09-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0018_injectionforoutpatient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outpatient_payments',
            name='ecg',
        ),
    ]
