# Generated by Django 4.0.3 on 2022-10-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0020_doctorcheckupamount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorcheckupamount',
            options={'default_permissions': (), 'ordering': ['id'], 'verbose_name_plural': 'DoctorCheckupAmount'},
        ),
    ]
