# Generated by Django 4.0.6 on 2022-10-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0021_alter_doctorcheckupamount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpatient_payments',
            name='doctor_check',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='outpatient_payments',
            name='payment_recived_by_doctor',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
