# Generated by Django 4.0.6 on 2022-11-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0024_appointment_medical_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpatient_payments',
            name='payment_recived_by_lab',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
