# Generated by Django 4.0.6 on 2022-11-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0027_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='comorbids',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='compliance',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='review_next_visit',
            field=models.DateTimeField(null=True),
        ),
    ]
