# Generated by Django 4.0.3 on 2022-11-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0028_appointment_comorbids_appointment_compliance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpatient_payments',
            name='payment_recived_by_xray',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
