# Generated by Django 4.0.6 on 2022-12-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0031_outpatient_paymenttransactions_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestforoutpatient',
            name='lab_canceled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='scanforoutpatient',
            name='scan_canceled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='xrayforoutpatient',
            name='xray_canceled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
