# Generated by Django 4.0.3 on 2023-01-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0034_outpatient_payments_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_emergency',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
