# Generated by Django 4.0.6 on 2023-01-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0035_appointment_is_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineforoutpatient',
            name='sale_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
