# Generated by Django 4.0.6 on 2023-01-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0036_medicineforoutpatient_sale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectionforoutpatient',
            name='sale_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
