# Generated by Django 4.0.6 on 2023-01-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0037_injectionforoutpatient_sale_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='health_checkup_details',
            field=models.JSONField(null=True),
        ),
    ]
