# Generated by Django 4.0.6 on 2023-01-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0038_appointment_health_checkup_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reports',
            field=models.ImageField(null=True, upload_to='images/op_uploaded_reports/%Y'),
        ),
    ]
