# Generated by Django 4.0.6 on 2023-01-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0040_remove_appointment_reports_op_uploadedreportsfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpatient_payments',
            name='refund',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='outpatient_payments',
            name='total_after_refund',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='outpatient_paymenttransactions',
            name='refund',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='outpatient_paymenttransactions',
            name='total_after_refund',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
