# Generated by Django 4.0.6 on 2023-01-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0041_outpatient_payments_refund_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpatient_payments',
            name='pulse',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='outpatient_payments',
            name='refund_note',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='outpatient_payments',
            name='refund_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
