# Generated by Django 4.0.6 on 2023-01-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0042_outpatient_payments_pulse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outpatient_payments',
            name='pulse',
        ),
    ]
