# Generated by Django 4.0.6 on 2023-02-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0043_remove_outpatient_payments_pulse'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestforoutpatient',
            name='payment_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
