# Generated by Django 4.0.6 on 2023-01-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheckupmaster',
            name='unit',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
