# Generated by Django 4.1 on 2022-09-19 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wards',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ward_name', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Wards',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='WardBed',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bed_no', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('vacancy_status', models.IntegerField(default=0, null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ward.wards')),
            ],
            options={
                'verbose_name_plural': 'WardBed',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
