# Generated by Django 4.1 on 2022-09-20 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_gender'),
        ('ward', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignWard',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateTimeField(null=True)),
                ('reason', models.TextField(default='', null=True)),
                ('discharged_date', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('payment_pending', models.BooleanField(default=True, null=True)),
                ('initially_paid', models.BooleanField(default=False, null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ward.wards')),
                ('ward_bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ward.wardbed')),
            ],
            options={
                'verbose_name_plural': 'AssignWard',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
