# Generated by Django 4.1 on 2022-09-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0003_doctercheckup_ward_xrayforwardpatient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignward',
            name='checkup',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='assignward',
            name='doctor_prescription',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='assignward',
            name='has_lab',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='assignward',
            name='has_xray',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
