# Generated by Django 4.1 on 2022-09-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0004_assignward_checkup_assignward_doctor_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wards',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
