# Generated by Django 4.1 on 2022-09-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0006_ward_patient_payments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ward_patient_paymenttransactions',
            old_name='ip_payment',
            new_name='ward_payment',
        ),
    ]
