# Generated by Django 4.1 on 2022-09-27 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0008_dischargesummary_ward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dischargesummary_ward',
            old_name='ip_no',
            new_name='ward_no',
        ),
    ]
