# Generated by Django 4.1 on 2022-09-27 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_gender'),
        ('ward', '0009_rename_ip_no_dischargesummary_ward_ward_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='DressingForWardPatient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dressing', models.CharField(max_length=100, null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('assignward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ward.assignward')),
                ('doctor_checkup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ward.doctercheckup_ward')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient')),
            ],
            options={
                'verbose_name_plural': 'DressingForWardPatient',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
