# Generated by Django 4.1 on 2022-09-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0011_ward_patient_payments_total_after_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignward',
            name='doctor_prescription',
        ),
        migrations.AddField(
            model_name='doctercheckup_ward',
            name='doctor_prescription',
            field=models.TextField(default='', null=True),
        ),
    ]
