# Generated by Django 4.0.6 on 2022-10-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0012_remove_assignward_doctor_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctercheckup_ward',
            name='medical_prescription',
            field=models.TextField(default='', null=True),
        ),
    ]
