# Generated by Django 4.0.6 on 2022-11-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0013_doctercheckup_ward_medical_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward_patient_payments',
            name='payment_recived_by_lab',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
