# Generated by Django 4.0.6 on 2022-11-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0014_ward_patient_payments_payment_recived_by_lab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ward_patient_payments',
            old_name='others',
            new_name='consultant_charges',
        ),
        migrations.RenameField(
            model_name='ward_patient_payments',
            old_name='service',
            new_name='dressing_charges',
        ),
        migrations.AddField(
            model_name='ward_patient_payments',
            name='establishment_charges',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ward_patient_payments',
            name='icu_charges',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ward_patient_payments',
            name='iv_fluid_charges',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ward_patient_payments',
            name='miscellaneous_charges',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ward_patient_payments',
            name='nursing_charge',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ward_patient_payments',
            name='physiotherapy_charges',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='ward_patient_payments',
            name='surgery_charges',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
