# Generated by Django 4.0.3 on 2022-11-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0018_assignward_has_scan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward_patient_paymenttransactions',
            name='department',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
