# Generated by Django 4.0.6 on 2022-12-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0019_ward_patient_paymenttransactions_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestforwardpatient',
            name='lab_canceled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='scanforwardpatient',
            name='scan_canceled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='xrayforwardpatient',
            name='xray_canceled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
