# Generated by Django 4.0.3 on 2022-11-30 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ward', '0019_ward_patient_paymenttransactions_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0031_outpatient_paymenttransactions_department'),
        ('patient', '0003_patient_pos_id'),
        ('room', '0024_in_patient_paymenttransactions_department'),
        ('scan', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanforpatient',
            name='card',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='scanforpatient',
            name='cash',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='scanforpatient',
            name='upi',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='ScanPaymentTransaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_type', models.CharField(max_length=200, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('existing_balance', models.IntegerField(default=0, null=True)),
                ('paid', models.IntegerField(default=0, null=True)),
                ('balance', models.IntegerField(default=0, null=True)),
                ('cash', models.IntegerField(default=0, null=True)),
                ('upi', models.IntegerField(default=0, null=True)),
                ('card', models.IntegerField(default=0, null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.appointment')),
                ('assignroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='room.assignrooms')),
                ('assignward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ward.assignward')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient')),
                ('scan_for_patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scan.scanforpatient')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ScanPaymentTransaction',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
