# Generated by Django 4.0.6 on 2023-02-09 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patient_id'),
        ('scan', '0004_scantakenbypatient_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanForDirectPatient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_type', models.CharField(max_length=100, null=True)),
                ('doctor_name', models.CharField(max_length=100, null=True)),
                ('initially_paid', models.BooleanField(default=False, null=True)),
                ('payment_pending', models.BooleanField(default=True, null=True)),
                ('total_amount', models.IntegerField(default=0, null=True)),
                ('discount', models.IntegerField(default=0, null=True)),
                ('total_after_discount', models.IntegerField(default=0, null=True)),
                ('paid', models.IntegerField(default=0, null=True)),
                ('balance', models.IntegerField(default=0, null=True)),
                ('cash', models.IntegerField(default=0, null=True)),
                ('upi', models.IntegerField(default=0, null=True)),
                ('card', models.IntegerField(default=0, null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient')),
            ],
            options={
                'verbose_name_plural': 'ScanForDirectPatient',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
