# Generated by Django 4.0.6 on 2023-02-09 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0005_scanfordirectpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantakenbypatient',
            name='scan_for_direct_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scan.scanfordirectpatient'),
        ),
    ]
