# Generated by Django 4.0.6 on 2023-02-13 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0006_scantakenbypatient_scan_for_direct_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantakenbypatient',
            name='scan_for_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scan.scanforpatient'),
        ),
    ]
