# Generated by Django 4.0.6 on 2023-02-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0007_alter_scantakenbypatient_scan_for_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanfordirectpatient',
            name='payment_complete',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='scanfordirectpatient',
            name='scan_canceled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='scanfordirectpatient',
            name='scan_checked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='scanfordirectpatient',
            name='scan_test',
            field=models.JSONField(null=True),
        ),
    ]
