# Generated by Django 4.0.6 on 2023-02-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0010_scanpaymenttransaction_scan_for_direct_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanpaymenttransaction',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='scanpaymenttransaction',
            name='total_after_discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
