# Generated by Django 4.0.6 on 2023-02-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0011_scanpaymenttransaction_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanpaymenttransaction',
            name='scan_test',
            field=models.JSONField(null=True),
        ),
    ]
