# Generated by Django 4.1.2 on 2023-06-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0014_alter_scan_created_time_alter_scan_updated_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
