# Generated by Django 4.1.2 on 2023-06-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0016_alter_scanfordirectpatient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanfordirectpatient',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scanforpatient',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scanpaymenttransaction',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scantakenbypatient',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
