# Generated by Django 4.0.3 on 2022-07-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('dob', models.DateField(null=True)),
                ('phone', models.CharField(max_length=150, null=True)),
                ('father_name', models.CharField(max_length=150, null=True)),
                ('address', models.TextField(default='', null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Patient',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
