# Generated by Django 4.1 on 2022-09-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pos_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
