# Generated by Django 4.0.3 on 2022-08-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'LabGroup',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
