# Generated by Django 4.0.3 on 2022-08-08 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True)),
                ('normal_range', models.CharField(max_length=100, null=True)),
                ('unit', models.CharField(max_length=100, null=True)),
                ('is_radio', models.BooleanField(default=False, null=True)),
                ('radio_test_range', models.CharField(max_length=100, null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lab.labgroup')),
            ],
            options={
                'verbose_name_plural': 'LabTest',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
