# Generated by Django 4.0.3 on 2022-08-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_labtest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='radio_test_range',
        ),
    ]
