# Generated by Django 4.0.3 on 2022-08-23 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_gender'),
        ('appointment', '0006_appointment_initially_paid'),
        ('lab', '0003_remove_labtest_radio_test_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestForPatient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('from_op', models.BooleanField(default=False, null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('appointment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appointment.appointment')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient')),
            ],
            options={
                'verbose_name_plural': 'LabTestForPatient',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TestTakenByPatient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('testunit', models.CharField(max_length=100)),
                ('testvalue', models.CharField(max_length=100)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('lab_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lab.labgroup')),
                ('lab_test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lab.labtest')),
                ('lab_test_for_patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lab.labtestforpatient')),
            ],
            options={
                'verbose_name_plural': 'TestTakenByPatient',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
