# Generated by Django 4.0.6 on 2022-11-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_remove_labtestforpatient_from_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestforpatient',
            name='doctor_checkup',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
