# Generated by Django 4.0.6 on 2022-11-04 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_pos_id'),
        ('lab', '0011_rename_doctor_checkup_labtestforpatient_doctor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestforpatient',
            name='doctor_name',
        ),
        migrations.CreateModel(
            name='LabTestForDirectPatient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField(default=0, null=True)),
                ('patient_type', models.CharField(max_length=100, null=True)),
                ('doctor_name', models.CharField(max_length=100, null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patient.patient')),
            ],
            options={
                'verbose_name_plural': 'LabTestForDirectPatient',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
