# Generated by Django 4.0.6 on 2022-11-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_testtakenbypatient_lab_test_for_direct_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestfordirectpatient',
            name='total',
        ),
        migrations.AddField(
            model_name='labtestforpatient',
            name='balance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
