# Generated by Django 4.0.6 on 2022-11-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_remove_directpatient_paymenttransactions_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestforpatient',
            name='initially_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
