# Generated by Django 4.0.6 on 2022-11-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0017_labtestforpatient_initially_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestforpatient',
            name='compleate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
