# Generated by Django 4.0.6 on 2022-11-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_labtestforpatient_compleate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtestforpatient',
            old_name='compleate',
            new_name='complete',
        ),
    ]
