# Generated by Django 4.0.3 on 2022-11-26 05:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0003_patient_pos_id'),
        ('lab', '0020_directpatient_paymenttransactions_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DirectPatient_PaymentTransactions',
            new_name='LabPaymentTransaction',
        ),
        migrations.AlterModelOptions(
            name='labpaymenttransaction',
            options={'default_permissions': (), 'ordering': ['id'], 'verbose_name_plural': 'LabPaymentTransaction'},
        ),
    ]
