# Generated by Django 4.0.3 on 2022-11-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0022_rename_direct_payment_labpaymenttransaction_lab_for_direct_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestforpatient',
            name='card',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='labtestforpatient',
            name='cash',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='labtestforpatient',
            name='upi',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
