# Generated by Django 4.0.6 on 2022-12-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0023_labtestforpatient_card_labtestforpatient_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labgroup',
            name='section',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
