# Generated by Django 4.0.6 on 2023-01-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0024_labgroup_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='labgroup',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
