# Generated by Django 4.0.6 on 2023-01-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0025_labgroup_status_labtest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpaymenttransaction',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='labpaymenttransaction',
            name='total_after_discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='labtestfordirectpatient',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='labtestfordirectpatient',
            name='total_after_discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
