# Generated by Django 4.0.6 on 2023-01-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0026_labpaymenttransaction_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='input_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
