# Generated by Django 4.0.6 on 2023-02-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0027_labtest_input_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(default='', null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('created_time', models.DateTimeField(auto_now=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'LabCategory',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
