# Generated by Django 4.0.6 on 2023-02-01 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0028_labcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labgroup',
            name='section',
        ),
        migrations.AddField(
            model_name='labgroup',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lab.labcategory'),
        ),
    ]
