# Generated by Django 4.0.6 on 2023-02-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0030_labtestforpatient_op_lab_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestfordirectpatient',
            name='lab_test',
            field=models.JSONField(null=True),
        ),
    ]
