# Generated by Django 4.0.6 on 2023-02-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0033_labtestfordirectpatient_lab_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestfordirectpatient',
            name='payment_complete',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
