# Generated by Django 4.0.3 on 2023-04-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0035_alter_labcategory_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestforpatient',
            name='payment_complete',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
