# Generated by Django 4.1.2 on 2023-06-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0041_alter_labcategory_id_alter_labgroup_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labcategory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labgroup',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
