# Generated by Django 4.0.3 on 2022-07-28 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, null=True)),
                ('specialized', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('address', models.TextField(default='', null=True)),
                ('username', models.CharField(max_length=150, null=True)),
                ('created_time', models.DateTimeField(null=True)),
                ('updated_time', models.DateTimeField(null=True)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.role')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Doctor',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
