# Generated by Django 4.0.6 on 2023-01-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_doctor_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='health_checkup_master',
            field=models.JSONField(null=True),
        ),
    ]
