# Generated by Django 4.0.6 on 2023-01-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_doctor_health_checkup_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='health_checkup_master',
            field=models.JSONField(default=[], null=True),
        ),
    ]
